services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5001:5001"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    environment:
      - VITE_API_BASE_URL=http://localhost:5001
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge